### PR TITLE
Rspec testing

### PR DESCRIPTION
**Pull request by Aaron-RN**
Rspect tests created

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: . However, some requirements needs to be made in order for us to approve your project. check :arrow_down: 

- **[REQUIRED]** For each class, each public method should be tested
  - you have a few of them.
  - Each method is tested seperately within a 'describe' block.

- **[REQUIRED]** In `game_logic_spec` you need to use `require_relative` instead of just `require`.

- **[REQUIRED]** Configure your repository to display linter checks result.

### That's it :relieved: . When finished, kindly resubmit another code review request :pray: 

Happy coding
##### Ahmed Mahfoudh

**Comment by Aaron-RN** [comment]
> ### Great work 👏 . However, some requirements needs to be made in order for us to approve your project. check ⬇️
> * **[REQUIRED]** For each class, each public method should be tested
>   
>   * you have a few of them.
>   * Each method is tested seperately within a 'describe' block.
> * **[REQUIRED]** In `game_logic_spec` you need to use `require_relative` instead of just `require`.
> * **[REQUIRED]** Configure your repository to display linter checks result.
> 
> ### That's it 😌 . When finished, kindly resubmit another code review request 🙏
> Happy coding
> 
> ##### Ahmed Mahfoudh

Why require_relative? if require works? whats the difference?
I thought require_relative was only if the files were in the exact same folder

**Comment by Aaron-RN** [comment]
When reviewing please look at the stickler errors and realize that they are unavoidable.

**Review by Ispirett — CHANGES_REQUESTED** [review]
Hey!! @Aaron-RN @zhuchini Really good job so far :100:  :100: with changes made and the tests done.

**[Optional]** You can use --format documentation in your rspec file. This will log more verbose information to the console.

**[Required]**
You are missing tests for win and draw logic 
Also please fix stiicker.yml errrors

**Comment by Aaron-RN** [comment]
> Hey!! @Aaron-RN @zhuchini Really good job so far 💯 💯 with changes made and the tests done.
> 
> **[Optional]** You can use --format documentation in your rspec file. This will log more verbose information to the console.
> 
> **[Required]**
> You are missing tests for win and draw logic
> Also please fix stiicker.yml errrors

The win and draw logic is called via the game_over? public method of Board Logic... which was tested in 3 different test cases also please look at the stickler error and see it is not fixable... or not worth fixing

**Review by Ispirett — CHANGES_REQUESTED** [review]
OK great @Aaron-RN  @stratospherique   :+1:  :+1: 
you should add all 8 possible playing positions in context block and specify diagonally horizontal and
vertical. 

Also please add that file to the exclude section in the stickler.yml file 
like - "spec/spec_helper.rb."

**Review by stratospherique — APPROVED** [review]
### Great job implementing the suggested changes :clap: . Congrats, your project is approve :heavy_check_mark: and you may merge to **development**

Keep up the good work :muscle: 
**Ahmed Mahfoudh**

**Pull request merged**
